### ISSUE TITLE
Gestapelde staaf grafiek

### ISSUE THREAD

**Issue by stijnimaging** [ggdatascience/rapportage_monitor_gmj#1]
Voor het maken van een gestapelde staaf grafiek lijkt het me eenvoudig om een variant te maken voor de standaard staaf grafiek. 
Met het toevoegen van "{if(gestapeld == T) as_bar_stack(., dir = "vertical") & chart_data_labels(position = "ctr") else .}" op regel 168 kan dit worden ondervangen.
Voorwaarde is dat er geen groepering of uitsplitsing is.

De conditie else if in de functie content_plaatsen zal dan als volgt worden: 
  } else if(type == 'staafgrafiek gestapeld') {
    
    value <- type_staafgrafiek(data = data, gestapeld = T,
                                         basis = basis, basis_label = basis_label, referentie = referentie, referentie_label = referentie_label,
                                         omschrijving = omschrijving, indicator = indicator, uitsplitsing = uitsplitsing, groepering = groepering, 
                                         waarden = waarden, niveau = niveau, jaar = jaar)

**Comment by STVermeulen** [comment]
Dit grafiektype is in de laatste versie toegevoegd.
