### ISSUE TITLE
Error in type_percentage functie bij if(is.na(.)) ... argument is of length zero

### ISSUE THREAD

**Issue by AmberBerlijn** [ggdatascience/rapportage_monitor_gmj#10]
Wij krijgen de volgende error. Het lijkt in onderdeel 5 te zitten. Weet iemand wat er mis gaat? 

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157385834/d9c71fc4-9aeb-49f5-b2f1-0aaf280d5b83)

**Comment by STVermeulen** [comment]
Zou je het configuratie excel kunnen delen? Of een screenshot van de rapportconfiguratie en de slideconfiguratie die je hebt gebruikt?

**Comment by STVermeulen** [comment]
type_percentage functie is aangepast en deze error zou daarmee opgelost moeten zijn.
