### ISSUE TITLE
Missende gegevens in powerpoint

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/rapportage_monitor_gmj#16]
![PPT jeugd - respons](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/8f9d6674-7f5a-45ba-8388-b33becef6f5d)
![PPT jeugd - thuis](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/4c419931-e39c-452a-831a-17b589d42791)
![PPT jeugd - woont bij beide ouders](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/1b79a203-caaf-4d8b-9c4d-540ca48dd430)

Gisteren bij de uitleg hebben we succesvol het script voor één school gerund. Maar vandaag ontbreken er grafieken en cijfers in de powerpoints. We krijgen geen error in R, maar er komt een incomplete powerpoint uit. Het gaat om de responstabel, wonen bij beide ouders en de OKO vragen over thuis (zie bijlage). 

We hopen dat je ons kan helpen.

**Comment by STVermeulen** [comment]
Zou je een screenshot van de rapportconfiguratie en de slideconfiguratie willen delen?

**Comment by SBorsboom** [comment]
![slideconfiguratie](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/06213de1-ea2d-4e18-aabf-c012724c74c3)
![rapportconfiguratie](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/ea921e4e-f43d-4666-91c4-b079de17b31d)

![melding powerpoint](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157682445/bb8bfa1d-d1c5-4dc6-abb0-f2b2cc6b6430)

Hopelijk zijn deze configuraties duidelijk. We hebben niet veel gewijzigd aan de basis.
Bij het openen van de powerpoint krijgen we wel een melding en moeten we de powerpoint repareren (zie bijlage). Bij het eerste rapport ging dat goed.

**Comment by STVermeulen** [comment]
Zou je mij een mail willen sturen om een afspraak te maken. Dan kan ik meekijken.

**Comment by RikstjevB** [comment]
Hoi, wij hadden ook een lege responstabel. Bij ons kwam het doordat MBOKK3s31 overal missing werd na het runnen van onderstaande regel in het script:

data$MBOKK3S31 <- factor(data$MBOKK3S31, levels = c('Vmbo', 'Havo/Vwo'), ordered = T). 

Met onderwijsniveau missing waren er dus ook geen waardes in de responstabel. Wij hebben daarom bovenstaande regel vervangen door: 
data <- data %>%
  filter(MBOKK3S31 ==1 | MBOKK3S31==2) %>%
  mutate(MBOKK3S31=factor(MBOKK3S31, levels=c(1,2), labels=c('Vmbo', 'Havo/Vwo')))

**Comment by STVermeulen** [comment]
Dit probleem van de missende gegevens in de PowerPoint lag aan het feit dat ik tijdens de workshop de slideconfiguratie had gefilterd en daarom werden deze regels niet meegenomen. Dit probleem is verholpen door gebruik te maken van de meest recente versie van het script. Ik sluit dit issue af.

**Comment by SBorsboom** [comment]
De tip van Rikstje voor het vullen van de responstabel heb ik in het nieuwe script nog wel aangepast. 
Dank voor de tip!
