### ISSUE TITLE
Error PMAP (8) door groepering KLAS 2 en KLAS 4

### ISSUE THREAD

**Issue by MarjoleinStoopendaal** [ggdatascience/rapportage_monitor_gmj#17]
Ik krijg de volgende error, maar mij is niet duidelijk wat er mis gaat. In het configuratiebestand staat KLAS als variabele, zo heet deze ook in de data set. 
Kan iemand mij helpen? Heeft iemand anders hier ook last van? 

<img width="359" alt="Knipsel" src="https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157800900/fe2200a4-2ecb-44ed-b09a-9ff9aa21d942">

**Comment by STVermeulen** [comment]
Dit issue ben ik al een aantal keer tegen gekomen en ik werk aan een structurele oplossing.

Dit probleem wordt veroorzaakt doordat bij de variabele KLAS (en ook bij de indicatoren voor gender en onderwijsniveau) bepaalde labels worden meegegeven vanuit SPSS, bijvoorbeeld 0 = ander leerjaar en/of 9 = onbekend. Het scripts verwacht alleen de labels ('1 = Klas 2' en '2 = Klas 4'). Er zijn verschillende manier op dit op te lossen:

1. De overige labels verwijderen in SPSS verwijderen uit het databestand (dus 0 = ander leerjaar en/of 9 = onbekend)
2. Een nieuwe variabele aanmaken voor KLAS waarbij '1 = Klas 2' en '2 = Klas 4'.
3. De labels verwijderen in R, met behulp van onderstaande code. De eerste regel verwijdert het label voor de waarde 0 (ander leerjaar) en de tweede regel verwijdert het label voor de waarde 9 (onbekend):

**Voor het runnen van deze code moet het package 'labelled' geladen zijn.**

val_label(data$KLAS, 0) <- NULL
val_label(data$KLAS, 9) <- NULL

Met onderstaande code kun je checken of je nu alleen nog de labels '1 = Klas 2' en '2 = Klas 4' hebt:

val_labels(data$KLAS)

Hopelijk lukt het op een van de bovenstaande manieren, anders hoor ik het graag.

**Comment by MarjoleinStoopendaal** [comment]
Het is gelukt, dank!
