### ISSUE TITLE
Error veroorzaakt door een lege cel. 0 personen ja hebben aangekruist bij een variabele

### ISSUE THREAD

**Issue by RikstjevB** [ggdatascience/rapportage_monitor_gmj#18]
Helaas nog steeds de error veroorzaakt door een lege cel. Wel het meest recente R script gebruikt. Is er nog een andere oplossing?

![Afbeelding1](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/158152013/f4eb1023-b0ba-4804-b334-3d208bf1af1c)

**Comment by STVermeulen** [comment]
Als het goed is kan deze error niet meer voorkomen in de laatste versie van het script. Blijft het probleem toch bestaan dan kun je voor het derde rapport een aangepaste slideconfiguratie gebruiken waarbij je de 67e regel uit de slideconfiguratie in Excel haalt (67 omdat in Excel de kolomnamen als regel 1 worden meegeteld en in R niet).
