### ISSUE TITLE
Mogelijk om datapunt 2023 toe te voegen in de trendgrafieken?

### ISSUE THREAD

**Issue by RikstjevB** [ggdatascience/rapportage_monitor_gmj#19]
Als de school geen data heeft in 2019 en 2021 dan is er in de trendgrafiek logischerwijs alleen een lijn voor de regio. Is het wellicht mogelijk om dan voor de school nog wel het datapunt van 2023 te laten zien? Zie hieronder een voorbeeld uit rapportage 2021.

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/158152013/a0b94ecc-8347-433d-a6ec-4ed55aff14dc)

**Comment by STVermeulen** [comment]
Ik ga er mee aan de slag.
