### ISSUE TITLE
Hoogte Y-as

### ISSUE THREAD

**Issue by stijnimaging** [ggdatascience/rapportage_monitor_gmj#2]
De limiet van de Y-as is nu vastgezet op 1. Dit lijkt te maken te hebben met de data, die verschilt tussen 0 en 1. 
In de grafiekstijl staat de limiet_max op 1; "chart_ax_y(limit_min = 0, num_fmt = '0%', major_tick_mark = 'none', limit_max = ylimiet)".

 Nu is dit zo standaard ingesteld en zou dit omgezet moeten kunnen worden naar de maximum waarde in de grafiek. Echter de waarden die in "y = 'val'" staan laten het niet toe om hier een maximum flexibel uit te halen. Wellicht dat dit op het verkeerde punt ingezet is.

**Comment by STVermeulen** [comment]
Dit is aangepast in de laatste versie van het script. De limiet van de y-as is nu 1 (tot 100%) als de maximumwaarde in de grafiek gelijk is of hoger dan 50%. De limiet van de y-as is 0.5 (tot 50%) als de maximumwaarde in de grafiek lager is dan 50%.
