### ISSUE TITLE
Error door lege cel

### ISSUE THREAD

**Issue by JudithSchuijs** [ggdatascience/rapportage_monitor_gmj#20]
Error in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 4.
Caused by error in `if (is.na(.)) ...`:
! argument is of length zero

**Comment by STVermeulen** [comment]
Dit probleem is als het goed is verholpen in het nieuwe script. Kun je het proberen met de meest recente versie?

**Comment by RikstjevB** [comment]
@STVermeulen bij mij werkt het nu. Bedankt! Wel een gek resultaat bij slide 5:

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/158152013/8f64524d-60a9-468b-b6a4-a5743fc730be)

Overigens, als de cel 0 is wordt het nu een '-' maar zou het niet gewoon 0% moeten zijn? vb: 0 van de 134 leerlingen heeft meegemaakt dat iemand tegen de zin een naaktfoto of filmpje heeft verspreid
