### ISSUE TITLE
LBGEK3S3 ipv LBGEK3S4 (vapen)?

### ISSUE THREAD

**Issue by mariellederijk** [ggdatascience/rapportage_monitor_gmj#21]
LBGEK3S4 = ooit vape gebruikt en LBGEK3S3 Vapet (minimaal wekelijks). In configuratie is LBGEK3S4 omschreven als vapet minimaal wekelijks.

**Comment by STVermeulen** [comment]
Ik heb de configuratie aangepast en nu wordt LBGEK3S3 gebruikt.

**Comment by Abeij** [comment]
LET OP: dit moet ook nog in de 'combi-grafiek' aangepast worden.
