### ISSUE TITLE
Error in referentie?

### ISSUE THREAD

**Issue by JudithSchuijs** [ggdatascience/rapportage_monitor_gmj#22]
Ik krijg deze error:

Error in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 9.
Caused by error in `filter()`:
ℹ In argument: `&...`.
Caused by error in `vec_equal()`:
! Can't combine `..1` <character> and `..2` <double>.

Ik dacht dat het probleem in de referentie zat. Ik heb daar ipv totaal en totaal nu GGDregio_school en GGD Zeeland ingevuld. Of werkt het niet zo en moet ik een aparte kolom hebben in mijn dataset die referentie heet?

**Comment by STVermeulen** [comment]
Deze error heb ik nog niet eerder gezien, maar wellicht komt het door de basis en referentie variabele die je hebt gebruikt. Het is van belang dat zowel de basis als de referentie variabele een string variabele is. Oftewel in de variabele die je voor de scholen gebruikt moet in de cellen de schoolnaam staan (en dus niet de schoolcode). Ook de referentie variabele moet als celwaarden tekst bevatten en geen numerieke waarden. Deze tekst in de celwaarden moet overeen komen met de tekst die je invult in de rapportconfiguratie bij de kolommen basis_label en referentie_label.

Stel je rapportconfiguratie ziet er zo uit:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sanderve/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sanderve/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


basis | basis_label | referentie | referentie_label | slideconfiguratie
-- | -- | -- | -- | --
Schoolnaam | College van de Hoge Hoed | opleiding | vmbo | Slideconfiguratie 1
Schoolnaam | College van de Grote Boom | opleiding | havo/vwo | Slideconfiguratie 1



</body>

</html>


Dan moet je data er zo uit zien:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sanderve/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sanderve/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Schoolnaam | opleiding
-- | --
College van de Hoge Hoed | vmbo
College van de Hoge Hoed | vmbo
College van de Hoge Hoed | vmbo
College van de Hoge Hoed | vmbo
College van de Grote Boom | havo/vwo
College van de Grote Boom | havo/vwo
College van de Grote Boom | havo/vwo
College van de Grote Boom | havo/vwo



</body>

</html>
