### ISSUE TITLE
Labels worden niet goed weergegeven

### ISSUE THREAD

**Issue by Abeij** [ggdatascience/rapportage_monitor_gmj#23]
![Dia14](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/b8aa94e6-ef43-4e01-b9bd-5b32ea6179fa)

Hier gaat iets niet goed met de labels, bij de middelste kolommen ontbreekt de legenda.
In de configuratietabel lijkt het wel goed benoemd te zijn, zie onderstaande afbeelding.

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/e6e56949-f2d1-42d0-b622-0c4e68d14b91)

**Comment by simoneverdiesen** [comment]
Suïcidegedachten is een te lang woord om op deze plaats weer te geven. Ik heb dit opgelost door een spatie toe te voegen tussen suïcide en gedachten.

**Comment by Abeij** [comment]
Weet iemand een oplossing om deze labels goed weer te geven? Zie bijgevoegd plaatje.
![GMJ](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/ec137740-eda0-4b8a-a1b6-830d8e37be7f)

**Comment by Abeij** [comment]
Een soortgelijke vraag geldt voor onderstaande
![GMJ](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/e7b44baf-a1c6-4e98-91bf-80522015a6f4)
 grafiek.

**Comment by Abeij** [comment]
Ik heb de labels ingekort, waardoor het nu wel past.
