### ISSUE TITLE
Bewegen: trend of niet?

### ISSUE THREAD

**Issue by Abeij** [ggdatascience/rapportage_monitor_gmj#24]
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/01c39f8d-75ce-4499-af12-be0e367dd548)
Wat is het idee vanuit de landelijke werkgroep? Nu lijken de wensen niet overeen te komen: staafgrafiek vs trendgrafiek.

**Comment by STVermeulen** [comment]
Ik heb de vraag doorgezet naar de het inhoudsgroepje. Zodra ik antwoord heb, zal ik dat hier posten.

**Comment by STVermeulen** [comment]
De vraagstelling van bewegen is veranderd en dus moet het een staafgrafiek zijn en geen trendgrafiek. Dit is al aangepast in de configuratie die op Github staat dus daarmee sluit ik dit issue.
