### ISSUE TITLE
Valuelabels worden niet in gestapelde staafgrafieken overgenomen

### ISSUE THREAD

**Issue by simoneverdiesen** [ggdatascience/rapportage_monitor_gmj#25]
Ik heb de valuelabels in het configuratiebestand aangepast, maar deze worden niet over genomen bij gestapelde staafgrafieken. Bij andere grafieksoorten gaat dit wel goed. Is er misschien een aanpassing nodig in de grafiekfunctie?

![vertrouwen in toekomst configuratie](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157618270/38c37952-cd56-443e-9ada-40b0d59c3254)
![vertrouwen in toekomst profiel](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157618270/7f4206f5-dc4d-4f80-9f08-f0f491f65524)

**Comment by STVermeulen** [comment]
Ik heb gekeken naar een aanpassing van de functie voor een gestapelde staafgrafiek, maar dat zorgt ervoor dat er weer andere errors ontstaan wanneer bijvoorbeeld voor een specifieke school een van de categorieën ontbreekt. De beste oplossing is dus een aanpassing van de data. Je kunt de labels van de variabele aanpassen (of een nieuwe variabele maken met andere labels en deze gebruiken in de slideconfiguratie). Bij deze specifieke variabele is het ook niet nodig om in de labels ook 'vertrouwen in de toekomst' te hebben.
