### ISSUE TITLE
Error wanneer een optie 0 keer is aangeklikt (Caused by error in 'chart_data_fill()')

### ISSUE THREAD

**Issue by LBeek** [ggdatascience/rapportage_monitor_gmj#26]
Het script loopt vast wanneer een optie in een kruistabel 0 keer is aangeklikt. Het probleem ligt niet bij de uitsplitsingsvariabelen want deze zijn juist gelabeld. Ik krijg bij meerdere rapportages onderstaande error:
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/159032068/b4202688-e702-454d-b0b1-8bec26deaf79)

**Comment by STVermeulen** [comment]
Ik ben bezig met een structurele oplossing. Je zou als tijdelijke oplossing voor deze school bij deze regel (regel 13 van je slideconfiguratie) niet kunnen uitsplitsen of groeperen op KLAS.

**Comment by STVermeulen** [comment]
Deze error is opgelost in de laatste versie van het script.
