### ISSUE TITLE
Foutmelding bij responstabel bij school met alleen klas 2 en niet alle schooltypen

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/rapportage_monitor_gmj#29]
Bij het runnen van het script, krijg ik de volgende foutmelding:

Error in pmap():
i In index: 3.
Caused by error in pmap():
i In index: 3.
Caused by error in get_rows_id():
! invalid row selection: out of range selection
Run rlang::last_trace() to see where the error occurred

Bovenstaande error verschijnt bij school waar maar 1 onderwijsniveau is en dan alleen klas 2. Alleen klas weghalen in Excel helpt niet.
Wat kan ik nog meer proberen?

**Comment by STVermeulen** [comment]
Ik zal uiterlijk morgen een aanpassing van het script plaatsen waarbij je wat meer mogelijkheden hebt om een responstabel uit te draaien.

**Comment by STVermeulen** [comment]
Ik hoop dat dat probleem ook verholpen is in de komende versie van het script. Zo niet, dan maken we een afspraak en kijken we er samen nog een keer naar.

**Comment by Abeij** [comment]
Helaas krijg ik met het nieuwe script een foutmelding, over de responstabel. Zie onderstaande afbeelding.
@STVermeulen: weet je hoe dit op te lossen is? Anders is het fijn om een afspraak te maken. Alvast bedankt!

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/461e1379-1437-45f3-855b-cc399e0b35e6)

**Comment by SBorsboom** [comment]
Helaas is bij ons de responstabel ook nog leeg en krijg ik nog dezelfde foutmelding als eerst. als ik de regel met de responstabel verwijder, kan ik de rest wel uitdraaien.
Ik krijg de volgende melding:

Error in `pmap()`:
? In index: 1.
Caused by error in `pmap()`:
? In index: 3.
Caused by error in `get_rows_id()`:
! invalid row selection: out of range selection
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/purrr_error_indexed>
Error in `pmap()`:
? In index: 1.
Caused by error in `pmap()`:
? In index: 3.
Caused by error in `get_rows_id()`:
! invalid row selection: out of range selection
---
Backtrace:
     ?
  1. +-purrr::pmap(...)
  2. ¦ +-purrr:::pmap_("list", .l, .f, ..., .progress = .progress)
  3. ¦   +-purrr:::with_indexed_errors(...)
  4. ¦   ¦ +-base::withCallingHandlers(...)
  5. ¦   +-purrr:::call_with_cleanup(...)
  6. ¦   +-global .f(...)
  7. ¦     +-purrr::pwalk(...)
  8. ¦       +-purrr::pmap(.l, .f, ..., .progress = .progress)
  9. ¦         +-purrr:::pmap_("list", .l, .f, ..., .progress = .progress)
 10. ¦           +-purrr:::with_indexed_errors(...)
 11. ¦           ¦ +-base::withCallingHandlers(...)
 12. ¦           +-purrr:::call_with_cleanup(...)
 13. ¦           +-global .f(...)
 14. ¦             +-global type_tabel(...)
 15. ¦               +-... %>% width(width = 5.85, unit = "cm")
 16. +-flextable::width(., width = 5.85, unit = "cm")
 17. ¦ +-flextable:::get_columns_id(x[["body"]], j)
 18. +-flextable::height_all(., height = 1.03, unit = "cm")
 19. ¦ +-flextable::height_all(x, height = height, part = i)
 20. ¦   +-flextable::nrow_part(x, part)
 21. +-flextable::set_table_properties(., layout = "fixed")
 22. +-flextable::border_inner_v(...)
 23. +-flextable::border_inner_h(...)
 24. +-flextable::border_outer(...)
 25. +-flextable::color(., color = "white", part = "all")
 26. +-flextable::bg(...)
 27.   +-flextable:::get_rows_id(x[[part]], i)
 28.     +-base::stop("invalid row selection: out of range selection")
>
