### ISSUE TITLE
Statistische toets

### ISSUE THREAD

**Issue by stijnimaging** [ggdatascience/rapportage_monitor_gmj#3]
De tekstvergelijkingen met statistische toets staat niet in het huidige script, maar er was een update door Arne op 26-10: chi squared toegevoegd aan 'bereken_cijfers' functie, inclusief suggestie voor uitspraak over 'hoger'/'lager'. Het lijkt me dat dit erin gezet kan worden (met de optie toetsen = T erbij). Of is er sinds 26-10 een aanpassing geweest? 
Te vinden in de history van het script hier; https://github.com/ggdatascience/rapportage_monitor_gmj/commit/e71828fea5c5c193866bd8921f5418507882ed47

**Comment by STVermeulen** [comment]
De statistische toets had ik uit de vorige versie gelaten, maar is in de huidige versie weer onderdeel van de bereken_cijfers functie. Aan de tekstvergelijkingen/dynamische tekst wordt nog gewerkt.
