### ISSUE TITLE
Foutmelding

### ISSUE THREAD

**Issue by Abeij** [ggdatascience/rapportage_monitor_gmj#30]
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/904a1cea-6f79-4126-96c8-71cba2c4a151)

Ik snap deze melding niet.... Er zijn wel respondenten uit klas 2. Kan iemand helpen?

**Comment by STVermeulen** [comment]
Waarschijnlijk heeft deze school geen leerlingen in klas 4 (of klas 2). Hiervoor heb ik een aanpassing gemaakt in het script die ik uiterlijk morgen zal uploaden.

**Comment by Abeij** [comment]
Dat klopt inderdaad (<5 respondenten uit klas 4). Ik wacht het nieuwe script af. Dank je wel alvast!

**Comment by stijnimaging** [comment]
Heb je dit getest met het nieuwe script?
En nog een opmerking; als er geen uitsplitsing mogelijk is per klas, zul je dit ook uit de configuratie moeten halen. Advies is om de configuratie sheet in Excel te kopiëren en aan te passen. Vervolgens verwijs je naar die sheet op de rapportconfiguratie.

**Comment by STVermeulen** [comment]
Deze error is opgelost in de laatste versie van het script.
