### ISSUE TITLE
Ontbrekende variabele PBWBK3S7

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#32]
In het Exceldocument staat de variabele PBWBK3S7 (Goed voor zichzelf opkomen). Deze variabele komt niet voor in onze dataset en wordt ook helemaal niet aangemaakt in de syntax, waardoor we een error krijgen in R. Is dit een combivariabele wat zelf is aangemaakt?

![GMJ](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/160627653/5e7ad2e4-5761-4603-8e3d-7cea271dff32)

**Comment by STVermeulen** [comment]
> In het Exceldocument staat de variabele PBWBK3S7 (Goed voor zichzelf opkomen). Deze variabele komt niet voor in onze dataset en wordt ook helemaal niet aangemaakt in de syntax, waardoor we een error krijgen in R. Is dit een combivariabele wat zelf is aangemaakt?
> 
> ![GMJ](https://private-user-images.githubusercontent.com/160627653/306325760-5e7ad2e4-5761-4603-8e3d-7cea271dff32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDExNTksIm5iZiI6MTcwOTE0MDg1OSwicGF0aCI6Ii8xNjA2Mjc2NTMvMzA2MzI1NzYwLTVlN2FkMmU0LTU3NjEtNDYwMy04ZTNkLTdjZWEyNzFkZmYzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNzIwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc5ZDA1YTIwOGFlMzQzYWU5ZmRmYmUyZmJhNzA4YTRkODQ2MjBiY2U2YWNhYzQ5YjY5YzA5ODJhZmQyZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EHxaVyfiw0ECfdeGNOhQ0RcwbAmgmCqQwIoJRKt2Saw)

In een oudere versie van de Excel configuratie stond de indicator PBWBK3S7, maar dit had PBWBK3S2 moeten zijn. Je kan dit zelf aanpassen of de meest recente Excel configuratie van Github gebruiken.
