### ISSUE TITLE
Opmaak responstabel 

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#33]
Bij het aanmaken van een responstabel krijgen wij alleen de eerste 5 rijen te zien. De opmaak lijkt niet over te lopen op de overige rijen (grijs gemarkeerd in afbeelding), waardoor ze niet zichtbaar zijn. Hoe kunnen we dit oplossen?

 ![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/160627653/64b799ef-6600-4dce-980d-8370738a638e)

**Comment by STVermeulen** [comment]
Er zijn inmiddels een aantal aanpassingen gedaan aan de responstabel. Gebruik hiervoor het meest recente script en Excel configuratie.
