### ISSUE TITLE
Geen waardes zichtbaar in staafdiagrammen 

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#34]
Een aantal staafdiagrammen worden niet gevuld/blijven leeg in de rapportage, terwijl deze wel gegevens bevatten. Dit betreffen bijna alle figuren waar een vergelijking wordt gemaakt tussen school en regio. We krijgen geen error in R. Waar zou dit aan kunnen liggen? 

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/160627653/218efa70-a4ad-4496-a400-a3502dc2eecf)

**Comment by STVermeulen** [comment]
Het is wenselijk om in de trendfiguren bij de observaties een punt te plaatsen in de figuur. Hier ben ik mee bezig.

Als je alleen voor 2023 een cijfer wil uitdraaien dan zou ik in de slideconfiguratie alle regels waar trendgrafiek staat aanpassen naar staafgrafiek dan zie je de cijfers wel.
