### ISSUE TITLE
fout ontdekt in Configuratie - indicator PBVKK3S4

### ISSUE THREAD

**Issue by miyasecetin** [ggdatascience/rapportage_monitor_gmj#35]
In regel 53 van het Configuratiebestand heeft de indicator PBVKK3S4 'Moeilijk omgaan met stress' als valuelabel. Ik vermoed dat dit een foutje is, want de indicator heeft in het SPSS-bestand de volgende label:  Vindt het niet moeilijk om stressvolle gebeurtenissen te doorstaan. Zelf hebben wij de valuelabel in het Configuratiebestand veranderd naar 'Makkelijk omgaan met stress'.

**Comment by stijnimaging** [comment]
Dank voor je bijdrage! Valuelabels kunnen aangepast worden. Wij hebben het aangepast naar 'Vindt het niet moeilijk om stressvolle gebeurtenissen te doorstaan'
