### ISSUE TITLE
Volgorde labels/indicatoren in grafieken

### ISSUE THREAD

**Issue by Abeij** [ggdatascience/rapportage_monitor_gmj#36]
Is het mogelijk om de volgorde van de labels aan te passen? In onderstaande grafiek is het bijvoorbeeld niet wenselijk dat 'iets anders' bovenaan staat. De volgorde in de configuratietabel blijkt niet leidend, zie hieronder.
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/cb8bd3dc-c08b-4387-aaa6-888ad875008e)
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/157376691/78410aa4-3235-46a1-ba86-216af189eae1)

**Comment by stijnimaging** [comment]
Het is niet mogelijk om de volgorde van de labels aan te passen middels de configuratie. De volgorde is bepaald door de indicatornamen. Indicatornamen aanpassen kan een oplossing zijn en bij voorbeeld 'iets anders' omcoderen naar een hoger getal. Het is echter de vraag of dit wenselijk is.

**Comment by STVermeulen** [comment]
Dit is een probleem dat veroorzaakt wordt doordat Office in een horizontale staafgrafiek de indicatoren van beneden naar boven ordent. Wellicht dat we dit in de toekomst aanpassen door de labels omgekeerd te sorteren. 

Voor nu zou je in de slideconfiguratie bij horizontale figuren (zoals combi liggend) de volgorde van indicatoren (en de aangepaste labels) kunnen omkeren. Oftewel je zet de indicatoren andersom in de kolom 'indicator', dus in plaats van 'indicator1; indicator2; indicator3' zet je in de cel 'indicator3; indicator2; indicator1'. **Doe dit vervolgens ook in de kolom 'valuelabel' anders staan de labels niet bij de goede indicator!**
