### ISSUE TITLE
Error no selected row

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#39]
Ik krijg de volgende error: 

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/160627653/e9c4f74e-22cc-457a-846a-1802e4e05750)

Hoe kunnen we dit oplossen?

**Comment by PaulienHagedoorn** [comment]
Ik krijg precies dezelfde foutmelding en ook bij dezelfde indexnummers. Wij hebben geen OKO variabelen, dus die heb ik uit de Excel configuratie en de powerpoint gehaald. Dan gaat het als het goed is om de staafgrafiek 'vindt school hartstikke leuk'. Voor de uitsplitsing en groepering heb ik genoeg observaties.

Ook bij de functie voor het opsporen van de foutmelding krijg ik een foutmelding. 
![Schermafbeelding 2024-03-01 121118](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/159147376/721aa6d6-1582-40bc-8911-fc4a18d6beda)

**Comment by PaulienHagedoorn** [comment]
A gevonden! Als je de OKO slides uit de powerpoint gooit moet je ook even de slidenummers in de Excel configuratie aanpassen naar de juiste slide. Oeps ;).
