### ISSUE TITLE
Vergelijking

### ISSUE THREAD

**Issue by stijnimaging** [ggdatascience/rapportage_monitor_gmj#4]
In het script staat de functie type_vergelijking beschreven, maar deze functie bestaat nog niet. 
Als er nu een grafiek gemaakt dient te worden met als type vergelijking, zal er niets gebeuren?!

Hoe dient deze vergelijking te zijn? Welke parameters zijn nodig?

**Comment by STVermeulen** [comment]
Vergelijking functie is wel toegevoegd, maar er zijn nu in het slideoverzicht geen regels die hier gebruik van maken. Ik sluit dit issue, maar is wellicht iets om op te nemen met het inhoudsgroepje. Ik zal ook aangeven tijdens de workshops dat deze functionaliteit er is.
