### ISSUE TITLE
Staafgrafiek met basis en referentie

### ISSUE THREAD

**Issue by PaulienHagedoorn** [ggdatascience/rapportage_monitor_gmj#45]
Ik wil graag een staafgrafiek met alleen een groepering naar klas en uitgesplitst naar school en regio. Zoiets als dit:

![Gewenste grafiek](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/159147376/8b57f66e-155c-4bcc-947f-706ec3fa8b18)

Ik heb in de configuratie het niveau aangepast naar 'basis en referentie':
![configuratie](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/159147376/a5217182-b25c-4a42-8305-fe3d2cdf8c92)

Maar dan krijg ik alleen de totalen voor de school en voor de regio, zonder uitsplitsingen of groepering: 
![grafiek slide 2](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/159147376/7dd102a8-fa5b-4147-9c5f-2061ede44c8d)

Ik heb al verschillende opties geprobeerd in de configuratie, maar hij blijft alleen maar de totalen naar school en regio tonen. Is er manier om de uitsplitsingen/groeperingen er toch nog in te krijgen?

**Comment by STVermeulen** [comment]
Met het nieuwe script is het mogelijk om dit voor elkaar te krijgen.
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/70630170/bdc57261-d375-4822-863a-6d4020f3dde1)

Om dit voor de schoolrapportages te gebruiken moet je wel het configuratiebestand aanpassen. Hier zijn (om te kunnen wegen) verschillende wijzigingen aan gedaan.

Een deel van de wijzigingen vindt je in het README.md bestand op de hoofdpagina. (https://github.com/ggdatascience/rapportage_monitor_gmj/blob/main/README.md) Je kunt deze wijzigingen zelf aanbrengen in de configuratie voor je school. Of je kunt de configuratie voor de gemeenterapportages (https://github.com/ggdatascience/rapportage_monitor_gmj/tree/main/Gemeenterapportage) gebruiken als basis en deze aanpassen voor de schoolrapportages.

Om de bovenstaande grafiek te maken heb ik de volgende Rapportconfiguratie en Slideconfiguratie gebruikt:
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/70630170/f10f1b00-0073-4f77-a53b-834ba72a2ddf)
![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/70630170/57a28f85-8b95-4f31-94b6-011f10967324)
