### ISSUE TITLE
Indicatorenoverzicht 

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#48]
Waar staat het indicatorenoverzicht? Wij hebben deze niet kunnen vinden

**Comment by STVermeulen** [comment]
Het indicatorenoverzicht voor de schoolrapportage staat hier: https://github.com/ggdatascience/rapportage_monitor_gmj/tree/main/Schoolrapportage

Het indicatorenoverzicht voor de gemeenterapportage staat hier:
https://github.com/ggdatascience/rapportage_monitor_gmj/tree/main/Gemeenterapportage
