### ISSUE TITLE
Top 3

### ISSUE THREAD

**Issue by stijnimaging** [ggdatascience/rapportage_monitor_gmj#5]
Voor het type grafiek top 3 is er nog geen functie beschikbaar. Dit lijkt te gaan om een top 3 van een indicator met factoren. De functie type_top3 heeft nu geen inhoud. 
dplyr heeft hier een functie voor; "top3 <- data %>% top_n(3, indicator = indicator)"

**Comment by STVermeulen** [comment]
Dit grafiektype is in de laatste versie toegevoegd. Je kunt met dit grafiek type een top n bepalen. Wil je bijvoorbeeld een top 3 wil dan vul je in de configuratie bij type in 'top 3' en wil je bijvoorbeeld een top 5 dan vul je 'top 5' in, etc.
