### ISSUE TITLE
Error Gemeenterapportage 

### ISSUE THREAD

**Issue by KubraBngl** [ggdatascience/rapportage_monitor_gmj#50]
Bij het runnen van het R script voor gemeenterapportage krijgen wij de volgende error: 

Gemeente Delft slidenummer: 3 indicator: KLAS; MBOKK3S33; GENDERError in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 3.
Caused by error in `pmap()`:
ℹ In index: 1.
Caused by error in `filter()`:
ℹ In argument: `.[[niveau]] == niveau_waarde & .[[jaar_indicator]] %in% jaar`.
Caused by error in `.[[jaar_indicator]]`:
! Can't extract column with `jaar_indicator`.
✖ Subscript `jaar_indicator` must be a location, not a character `NA`.
Run `rlang::last_trace()` to see where the error occurred.

Ons Excel configuratiebestand ziet er zo uit:
![MicrosoftTeams-image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/160627653/d88ae6a0-c3cb-4428-ba1d-cca7eecafbf9)

Onderzoeksjaar is een numerieke variabele in SPSS

**Comment by STVermeulen** [comment]
Ik denk dat de error komt doordat in de kolom 'niveau_waarde' nu 'niveau' staat, maar hier moet de waarden van de indicatoren die je hebt opgegeven in de 'niveau_indicator' staan die je hebt opgegeven. Zo heb je de indicator Gemeentecode2023 opgegeven, dus moet je in de kolom niveau_waarde de waarde opgegeven voor de gemeente waarover het rapport gaat. De waarde is hetgeen wat in de cel staat voor een respondent van de desbetreffende gemeente. Dit kan een numerieke waarde zijn zoals meestal het geval is bij de Gemeentecode indicatoren, maar het kan ook tekst zijn. Dat is afhankelijk van hoe je Gemeentecode2023 hebt aangemaakt. Daarnaast heb je nog een 'niveau_indicator' opgegeven genaamd GGDregio. Hiervoor moet je ook de corresponderende waarde opgeven in de kolom 'niveau_waarde'. Je geeft dus net zoveel niveau waardes op (gescheiden door een puntkomma) als dat je niveau indicatoren op hebt gegeven.

Kortom als de waarde voor de Gemeentecode2023 van Delft 5 is en de waarde voor de GGDRegio is 12 dan vul je in de kolom 'niveau_waarde' het volgende in:

5; 12

**Comment by RikstjevB** [comment]
Ik krijg dezelfde foutmelding helaas. Bij mij is niveau_waarde wel ingevuld. Enig idee wat er fout gaat?

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/158152013/19f8976b-33b5-46a2-90f8-3216e1838b0e)

**Comment by STVermeulen** [comment]
Het lijkt erop alsof de variabele 'Onderzoeksjaar' niet in jullie data terugkomt. Zou een van jullie mij kunnen mailen/bellen dan kunnen we er samen naar kijken.

**Comment by MFlapper** [comment]
Ik kreeg dezelfde foutmelding (dan alleen bij het gewogen figurenboek OKO), maar is hetzelfde script. Wat bij mij heeft geholpen is om de variabele Gemeentecode2023 om te zetten in een string variabele (met onderstaande syntax). Hetzelfde zou ik dan ook doen voor de variabele GGDRegio_leerling voor de gemeenterapportage.

De rapportconfiguratie heb ik daarna zo ingevuld:

![github](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/161725814/a07f5618-9ca9-496f-a18f-5c2c59977360)

STRING Gemeente (A20).
RECODE Gemeentecode2023 (59='Achtkarspelen') (60='Ameland') (72='Harlingen') (80='Leeuwarden') (74='Heerenveen') (85='Ooststellingwerf') (86='Opsterland') (88='Schiermonnikoog')
     (90='Smallingerland') (93='Terschelling') (96='Vlieland') (98='Weststellingwerf') (737='Tytsjerksteradiel') (1900='Sudwest Fryslan') (1891='Dantumadiel') (1940='De Fryske Marren') (1970='NoardEast Fryslan') 
     INTO Gemeente.
VARIABLE LABELS  Gemeente 'Gemeente'.
EXECUTE.

**Comment by RikstjevB** [comment]
Ik heb toch nog een typfout gevonden in mijn tabblad van de gemeenteconfiguratie. Nu krijg ik geen foutcodes meer en wordt er wel een gemeenteprofiel aangemaakt (als ik regel 62 met prestatiedruk verwijder). 

Helaas blijkt het profiel grotendeels leeg. Alleen voor 2019 kan data worden weergegeven. Er lijkt iets niet te lukken met het wegen van de 2021 en 2023 data. Zou nog steeds heel fijn zijn als je even mee zou willen kijken!

**Comment by SBorsboom** [comment]
Wij hebben mbv de gemeente configuratie een profiel voor een gemeente gedraaid. Dat gaat goed, behalve voor de trend grafieken. Daarin zien we alleen cijfers voor 2023. In een SPSS combinatiebestand had ik ook 2021 opgenomen, maar die wordt niet weergegeven.
Ik ben benieuwd wat bij jullie de oplossing was.
