### ISSUE TITLE
Error OKO figurenboek (gewogen): no selected row

### ISSUE THREAD

**Issue by MFlapper** [ggdatascience/rapportage_monitor_gmj#52]
Hoi,

Het gewogen script (en dan in combinatie met OKO figurenboek) lijkt te werken tot rij 37 vrije tijd. 

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/161725814/3b34fd08-615a-47c1-a4f0-cc1d7b3ddf89)

Het lijkt alsof er geen 'gekoppelde locatie' is met de powerpoint? Als ik het template open in diamodel kan ik alleen niet zo goed ontdekken waar het mis gaat. Hij maakt vanuit het script meer slides aan zodra dat nodig is volgensmij?

![image](https://github.com/ggdatascience/rapportage_monitor_gmj/assets/161725814/3ae2b535-4fd3-4981-a449-0657060e40a0)

**Comment by StephanieBrinkhues** [comment]
Ik krijg dezelfde error, sinds ik het logo van onze GGD heb toegevoegd aan de template. In de versie van Sander zonder bewerkingen runt het bij mij wel zonder foutmeldingen.

**Comment by STVermeulen** [comment]
Deze error komt doordat de kolom 'slidenummer' moet worden doorgenummerd. Deze moet je dus aanpassen als je een nieuwe regel toevoegt of bepaalde regels verwijderd. Let hierbij op dat er soms 1 en soms 2 figuren op een slide moeten komen en je in dat geval dus hetzelfde slidenummer opgeeft voor deze regels.

**Comment by MFlapper** [comment]
Ah, ja hij doet het! Dank!!
