### ISSUE TITLE
2. Template.pptx can't be read_pptx nor opened via windows due to error in content

### ISSUE THREAD

**Issue by edissepo** [ggdatascience/rapportage_monitor_gmj#56]
Executing the R script '3. Rapportage.R', I get an error (Error in zip::unzip....) in regard to the template pptx file. When opening the file in Windows a messagebox says that it might be able to repair the damaged content but alas, it cannot.
Hopefully this is plenty info and you can fix this. Also, it seems incorrect that the template file is only 1kb.

**Comment by STVermeulen** [comment]
Volgens mij is dit issue opgelost, klopt dat?

**Comment by edissepo** [comment]
Correct. Thanks
