### ISSUE TITLE
OKO gewogen cijfers: Rapportage blijft leeg

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/rapportage_monitor_gmj#58]
We hebben geprobeerd het figurenboek uit te draaien met de gewogen cijfers.
Het script runt wel volledig, lijkt ook alle slides aan te maken, maar de rapportage blijft vervolgens leeg. Alleen op voorblad komt gemeentenaam te staan. Enig idee hoe dat kan?
[1. Configuratie Figurenboek.xlsx](https://github.com/ggdatascience/rapportage_monitor_gmj/files/14849122/1.Configuratie.Figurenboek.xlsx)

In de bijlage ons configuratie bestand. 
De gemeente hebben we als een string variabele opgenomen in het databestand.

**Comment by lkuijs** [comment]
Zijn er respondenten die geen weging hebben? Deze moet je dan weging 0 geven of uit het bestand halen. Dan krijg je wel data in je rapportage :)

**Comment by lkuijs** [comment]
Ah oké... Ik heb de respondenten zonder weegfactor uit mijn bestand gehaald, en toen werkte het bij mij wel. 
Mogelijk dat het nog helpt om dit issue te lezen: 'Deel van percentages of grafieken blijft leeg #51'

**Comment by SBorsboom** [comment]
Het verwijderen van de respondenten helpt inderdaad wel, ik krijg nu wel een gevuld figurenboek.
Dank voor het meedenken!
