### ISSUE TITLE
Paden naar bronbestanden geven error 

### ISSUE THREAD

**Issue by ggdgrojvk** [ggdatascience/rapportage_monitor_gmj#6]
Waarschijnlijk is dit te wijten aan de oude versie van R die wij gebruiken in Groningen (2021.09.02), maar ik wilde het iig melden just in case er meer mensen gaan zijn die geen nieuwe versie van R (mogen) draaien. (Wellicht iets extra's voor de documentatie).

Wat er gebeurt:
De bronbestanden template.pptx en configuratie.xlsx worden niet gevonden door R.

Waarschijnlijke oorzaak:
De relatieve paden die R gebruikt (in de set-up die wij hebben), zorgt ervoor dat de bestanden niet kunnen worden gevonden.

Oplossing: 
De bestanden worden wel gelezen indien volledige paden worden opgegeven.

**Comment by stijnimaging** [comment]
Het klopt dat het ingeven van volledige paden een oplossing is. Let wel dat dan / gebruikt is in de padnamen. 

Een andere oplossing is om de actieve map / working directory te wijzigen. Middels setwd("path/naar/directory/") kun je dit doen. Dit kan ook door bovenin te klikken op "Session"--> "Set Working Directory" --> "Choose Directory" (oftewel Ctrl + Shift +H).
In de working directory zul je dan de bronbestanden template.pptx en configuratie.xlsx beschikbaar moeten hebben. Ook het SPSS databestand (bijvoorbeeld 'Testdata GMJ2023.sav') zal in de betreffende working directory moeten staan.

**Comment by STVermeulen** [comment]
Ik heb de uitleg van Stijn over het instellen van de working directory toegevoegd aan de nieuwe versie van het script.
