### ISSUE TITLE
Error op kleurcode koppelen aan labels 

### ISSUE THREAD

**Issue by rblok81** [ggdatascience/rapportage_monitor_gmj#8]
In ons spss bestand hebben we bij KLAS maar drie categorieën (0,1,2), dus we krijgen onderstaande foutmelding: 
_Error in chart_data_fill(., kleuren[1:(val_labels(data[[groepering]]) %>%  : 
  values's names do not match series' names: "Ander leerjaar", "Klas 2", "Klas 4"_

Aanpassen _(kleuren[1:(val_labels(data[[groepering]]) %>% length())]_ naar _(kleuren[1:(**unique(**data[[groepering]]) %>% length())]_?

**Comment by STVermeulen** [comment]
Voor de variabele KLAS moet 'Ander leerjaar' missing zijn, want je bent waarschijnlijk alleen geïnteresseerd in Klas 2 en Klas 4. Dit zou eigenlijk standaard zo moeten zijn in de syntax, of er zou een een nieuwe dichotome variant voor KLAS moeten worden gemaakt.

**Comment by STVermeulen** [comment]
Deze error is opgelost in de laatste versie van het script.
