### ISSUE TITLE
Error bij #8 rapportages maken op basis van rapportconfiguratie

### ISSUE THREAD

**Issue by Abeij** [ggdatascience/rapportage_monitor_gmj#9]
> # 8. Rapportages maken op basis van rapportconfiguratie -------------------
> 
> pmap(.l = configuratie$Rapportconfiguratie, 
+      .f = rapportage_maken, data = data, configuratie = configuratie, template = '2. Template.pptx')
Error in vctrs_vec_compat(x, user_env) : object 'configuratie' not found

**Comment by Abeij** [comment]
En vandaag verschijnt deze melding:

> # 8. Rapportages maken op basis van rapportconfiguratie -------------------
> 
> pmap(.l = configuratie$Rapportconfiguratie, 
+      .f = rapportage_maken, data = data, configuratie = configuratie, template = '2. Template.pptx')
Error in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 4.
Caused by error in `if (is.na(.)) ...`:
! argument is of length zero
Run `rlang::last_error()` to see where the error occurred.

**Comment by STVermeulen** [comment]
Deze error in de type_percentage functie is opgelost in de laatste versie van het script.
